UniqueElement เเบบ n กำลังสอง

In [422]:
def UniqueElement(n):
    
    for i in range(len(n)):
        for j in range(i+1 , len(n)):
            if n[i] == n[j]:
                return False
    return True

In [423]:

UniqueElement([12,38,42,64,53,43,55,34,45,64,90,82])



False

PresortUniqueElement

In [424]:
def lomuto_partition(A, l, r):
        # p ← A[l]
        p = A[l]

        # s ← l
        s = l

        # for i ← l+1 to r do
        for i in range(l + 1, r + 1):

            # if A[i] < p then
            if A[i] < p:
                # s ← s + 1
                s = s + 1

                # swap(A[s], A[i])
                A[s], A[i] = A[i], A[s]

        # swap(A[l], A[s])
        A[l], A[s] = A[s], A[l]

        # return s
        return s
    

def quick_sort(A, l, r):
    if l < r:
        s = lomuto_partition(A, l, r)
        quick_sort(A, l, s - 1)   # ซ้ายของ pivot
        quick_sort(A, s + 1, r)   # ขวาของ pivot
            
    return A
            

In [425]:
B = [12,38,42,64,53,43,55,34,45,64,90,82]

piovot_index = lomuto_partition(B , 0 , len(B)-1) #ใช้ Lomuto partition algorithm เพื่อแบ่งอาร์เรย์



print("Array after partition:", B)
print("Pivot index:", piovot_index)

sum = quick_sort(B, 0, len(B) - 1)

print(sum)


#([12,38,42,64,53,43,55,34,45,64,90,82])




Array after partition: [12, 38, 42, 64, 53, 43, 55, 34, 45, 64, 90, 82]
Pivot index: 0
[12, 34, 38, 42, 43, 45, 53, 55, 64, 64, 82, 90]


In [426]:
def presort(A):
    for i in range(len(A)-1):
        if A[i] == A[i+1]:
            return False
    return True

In [427]:
presort(sum)

False

In [428]:
def forward_elimination_pure_python(A, b):
    n = len(A) # จำนวนแถว (ขนาด n)

    # 1. สร้าง Augmented Matrix (รวม A กับ b)
    # เราจะสร้างลิสต์ใหม่โดยเอาแถวของ A มาต่อด้วยสมาชิกของ b
    aug_matrix = []
    for i in range(n):
        # A[i][:] คือการ copy ข้อมูลแถว i ของ A
        # [b[i]] คือแปลงค่า b ตัวที่ i เป็นลิสต์ เพื่อเอามาต่อกัน
        new_row = A[i][:] + [b[i]] 
        aug_matrix.append(new_row)
    print(aug_matrix)

    # 2. เริ่มขั้นตอน Forward Elimination
    # Loop i: Pivot Row (แถวหลักที่จะใช้กำจัดแถวอื่น)
    # เทียบเท่า for i <- 1 to n-1
    for i in range(n - 1): 
        
        # Loop j: Target Row (แถวที่เราต้องการกำจัดตัวแปรข้างหน้า)
        # เทียบเท่า for j <- i+1 to n
        for j in range(i + 1, n):
            
            # ตรวจสอบตัวหารเป็น 0 หรือไม่ (เพื่อป้องกัน Error)
            if aug_matrix[i][i] == 0:
                print(f"Warning: Pivot ที่แถว {i} เป็น 0 อาจเกิด Error ได้")
                continue

            # คำนวณ Factor: ตัวคูณที่จะทำให้ aug_matrix[j][i] กลายเป็น 0
            factor = aug_matrix[j][i] / aug_matrix[i][i]

            # Loop k: ลบค่าในแต่ละคอลัมน์ของแถว j
            # เทียบเท่า for k <- i to n+1
            # เลื่อนไปทีละคอลัมน์ในแถว j แล้วคำนวณค่าใหม่
            for k in range(i, n + 1):
                aug_matrix[j][k] = aug_matrix[j][k] - (factor * aug_matrix[i][k])

    return aug_matrix



In [429]:
A = [
    [0, -1, 1],
    [3, 0, 9],
    [3, 3, 0]
]
b = [8, 0, 4]

# เรียกใช้งาน
result = forward_elimination_pure_python(A, b)

# แสดงผลลัพธ์ (วนลูป print เพื่อให้อ่านง่ายขึ้น)
print("Upper Triangular Matrix (Augmented):")
for row in result:
    # จัด format ให้ทศนิยม 2 ตำแหน่งเพื่อให้ดูง่าย
    print([f"{x:.2f}" for x in row])

[[0, -1, 1, 8], [3, 0, 9, 0], [3, 3, 0, 4]]
Upper Triangular Matrix (Augmented):
['0.00', '-1.00', '1.00', '8.00']
['3.00', '0.00', '9.00', '0.00']
['3.00', '3.00', '0.00', '4.00']


In [430]:
def BetterForward(A , b):
    aug_matrix = []
    for i in range(len(A)):
        new_row = A[i][:] + [b[i]] 
        aug_matrix.append(new_row)
    print(aug_matrix)
    
    for i in range(i+1 , len(A)):
        piovot = i
        for j in range(i+1 , len(A)):
            if A[j][i] > A[piovot][i]:
                pivot = j
        for k in range(len(A)):
            A[pivot][k],A[i][k] = A[i][k],A[pivot][k]
        for j in range(len(A)):
            temp = A[j][i] / A[i][i]
            for k in range(len(A)):
                A[j][k] = A[j][k] - A[i][k] *temp
    return A
                
    
    

In [431]:
A = [
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
]
b = [8, 0, 4]

# เรียกใช้งาน
result = BetterForward(A, b)

for row in result:
    # จัด format ให้ทศนิยม 2 ตำแหน่งเพื่อให้ดูง่าย
    print([f"{x:.2f}" for x in row])

[[2, -1, 1, 8], [3, 3, 9, 0], [3, 3, 5, 4]]
['2.00', '-1.00', '1.00']
['3.00', '3.00', '9.00']
['3.00', '3.00', '5.00']


In [432]:
A2 = [6,3,2,9,1,3,6,6,2,3,1,3,2,6,9,3,2,1,3]

piovot_index = lomuto_partition(A2 , 0 , len(A2)-1) #ใช้ Lomuto partition algorithm เพื่อแบ่งอาร์เรย์



print("Array after partition:", A2)
print("Pivot index:", piovot_index)

sum = quick_sort(A2, 0, len(A2) - 1)

print(sum)


#([12,38,42,64,53,43,55,34,45,64,90,82])






Array after partition: [3, 3, 2, 1, 3, 2, 3, 1, 3, 2, 3, 2, 1, 6, 9, 6, 9, 6, 6]
Pivot index: 13
[1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 9, 9]


In [433]:
def PresortMode(A):
    i = 0
    modefrequency = 0
    while i <= len(A)-1:
        runlength = 1 ; runvalue = A[i]
        while i + runlength <= len(A)-1 and A[i+runlength] == runvalue:
            runlength = runlength + 1
        if runlength > modefrequency:
            modefrequency = runlength
            modevalue = runvalue
        i = i + runlength
    return modevalue
            
        
            

In [434]:
PresortMode(sum)

3

In [435]:
def gcd (m, n):
    while n != 0:
        r = m % n
        m = n
        n = r
    return m

gcd(24, 60)

12

In [436]:
def lcm(m , n):
    sum = m*n / gcd(m,n)
    return sum

In [437]:
print(lcm(24,60))
print(lcm(11,5))

120.0
55.0


In [458]:
a= [6,3,2,9,1,3,6,6,2,3,1,3,2,6,9,3,2,13]
b={key: a.count(key) for key in a}
mode = max(b,key=b.get)

In [460]:
b

{6: 4, 3: 5, 2: 4, 9: 2, 1: 2, 13: 1}

In [459]:
mode

3

In [ ]:
import numpy as np
from scipy.linalg import solve_triangular

def simple_lu(A):
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy().astype(float)
    
    for i in range(n):
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j, i:] -= factor * U[i, i:]
            
    return L, U


A = np.array([[2, -1, 1],
              [4, 1, -1],
              [1, 1, 1]])
b = np.array([1, 5, 0])

L, U = simple_lu(A)

print("L matrix (ตรงตามรูป):\n", L)
print("U matrix (ตรงตามรูป):\n", U)

y = solve_triangular(L, b, lower=True)


x = solve_triangular(U, y, lower=False)

print(f"Step 1 (Ly = b): y1 = {y[0]:.0f}, y2 = {y[1]:.0f}, y3 = {y[2]:.0f}")
print(f"Step 2 (Ux = y): x1 = {x[0]:.0f}, x2 = {x[1]:.0f}, x3 = {x[2]:.0f}")

L matrix (ตรงตามรูป):
 [[1.  0.  0. ]
 [2.  1.  0. ]
 [0.5 0.5 1. ]]
U matrix (ตรงตามรูป):
 [[ 2. -1.  1.]
 [ 0.  3. -3.]
 [ 0.  0.  2.]]
Step 1 (Ly = b): y1 = 1, y2 = 3, y3 = -2
Step 2 (Ux = y): x1 = 1, x2 = 0, x3 = -1
